export const SPORTS_LIST =
    [
                { id: 1,
                  name:"Badminton",
                  reg_fee_men:'5000/-',
                  reg_fee_women:'2500/-',
                  location:'MIT Recreation Center',
                                
                },
                { id: 2,
                  name:"Handball",
                  reg_fee_men:'3000/-',
                  reg_fee_women:'NA',
                  location:'MIT Grounds',
                                
                },
                { id: 3,
                  name:"Cricket",
                  reg_fee_men:'7500/-',
                  reg_fee_women:'NA',
                  location:'MIT Cricket Field',
                                
                },
                { id: 4,
                  name:"Cross Country",
                  reg_fee_men:'1100/-',
                  reg_fee_women:'300/-',
                  location:'Athletics Field',
                                
                },
                { id: 5,
                  name:"Basketball",
                  reg_fee_men:'5500/-',
                  reg_fee_women:'4500/-',
                  location:'MIT Basketball Courts',
                                
                },
                { id: 6,
                  name:"Chess",
                  reg_fee_men:'2000/-',
                  reg_fee_women:'2000/-',
                  location:'MIT Academic Block 5',
                                
                },
                { id: 7,
                  name:"Football",
                  reg_fee_men:'7500/-',
                  reg_fee_women:'500/-',
                  location:'MIT Grounds',
                                
                },
                { id: 8,
                  name:"Swimming",
                  reg_fee_men:'Individual: 200/-  Relay:800/-',
                  reg_fee_women:'Individual: 200/-  Relay:800/-',
                  location:'MIT Swimming Pool',
                                
                },
                { id: 9,
                  name:"Volleyball",
                  reg_fee_men:'5000/-',
                  reg_fee_women:'4000/-',
                  location:'MIT Volleyball Court',
                                
                },
                { id: 10,
                  name:"Table Tennis",
                  reg_fee_men:'2000/-',
                  reg_fee_women:'500/-',
                  location:'MIT Recreation Center',
                                
                },
                { id: 11,
                  name:"Hockey",
                  reg_fee_men:'7500/-',
                  reg_fee_women:'NA',
                  location:'MIT Hockey Field',
                                
                },
                { id: 12,
                  name:"Throwball",
                  reg_fee_men:'NA',
                  reg_fee_women:'4000/-',
                  location:'Marena Sports Complex',
                                
                },
                { id: 13,
                  name:"Squash",
                  reg_fee_men:'550/-',
                  reg_fee_women:'400/-',
                  location:'Marena Sports Complex',
                                
                },
                { id: 14,
                  name:"Lawn Tennis",
                  reg_fee_men:'2000/-',
                  reg_fee_women:'500/-',
                  location:'Recreation Center',
                                
                },
                { id: 15,
                  name:"Athletics",
                  reg_fee_men:'Individual: 250/-    Relay:1000/-',
                  reg_fee_women:'Individual: 250/-  Relay:1000/-',
                  location:'MIT Recreation Center',
                                
                },
       
    ];